pid: /home/poh/Projects/kuromoji-web/thin.pid
log: /home/poh/Projects/kuromoji-web/thin.log
timeout: 30
port: 4567
max_conns: 1024
chdir: /home/poh/Projects/kuromoji-web/site_files
rackup: /home/poh/Projects/kuromoji-web/config.ru
max_persistent_conns: 512
environment: production
address: 127.0.0.1
servers: 1
daemonize: false
